import type { Metadata } from "next";
import { Lato } from "next/font/google";
import ThemeRegistry from '@/utils/ThemeRegisry';
import '@/theme/index.css'


const chicle = Lato({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-Br">
      <body className={chicle.className}>
        <ThemeRegistry options={{ key: 'mui-theme' }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
